### ISSUE TITLE
Syslog forwarder issues - BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by mutazalsallal** [sysflow-telemetry/sf-docs#37]
**Indicate project**
sf-exporter

**Describe the bug**
configured sysflow to push the logs to a remote syslog, after few hours I started to receive a huge duplicated events

BrokenPipeError: [Errno 32] Broken pipe

this is the error stack trace:

> 2020-02-05 21:48:48,864 [INFO]  Uploaded trace /mnt/data/1580939256
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 944, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "./exporter.py", line 220, in <module>
    exporter.run()
  File "/usr/local/exporter/executor.py", line 44, in run
    self.func(*self.params)
  File "./exporter.py", line 94, in run
    export_to_syslogger(args, logger)
  File "./exporter.py", line 110, in export_to_syslogger
    formatter.applyFuncJson(lambda sf: rsyslog(logger, sf, args.syslogexpint), fields)
  File "/usr/local/lib/python3.6/site-packages/sysflow-0.1-py3.6.egg/sysflow/formatter.py", line 172, in applyFuncJson
    func(json.dumps(record))
  File "./exporter.py", line 110, in <lambda>
    formatter.applyFuncJson(lambda sf: rsyslog(logger, sf, args.syslogexpint), fields)
  File "./exporter.py", line 72, in rsyslog
    logger.info(msg)
Message: '{"flow_type": "FF", "op_flags": "O  W    C  ", "ret_code": "", "ts": "02/05/2020T21:48:36.505842", "ts_uts": 1580939316505842351, "end_ts": "02/05/2020T21:48:36.505912", "end_ts_uts": 1580939316505911652, "proc_pid": 1, "proc_tid": 1, "proc_uid": 0, "proc_user": "root", "proc_gid": 0, "proc_group": "root", "proc_exe": "/usr/local/sysflow/bin/sysporter", "proc_args": "-G 60 -w /mnt/data/ -e ubuntu3 -f container.name!=sf-collector and container.name!=sf-exporter", "proc_tty": false, "proc_create_ts": 1580857027654511431, "pproc_pid": "", "pproc_gid": "", "pproc_uid": "", "pproc_group": "", "pproc_tty": "", "pproc_user": "", "pproc_exe": "", "pproc_args": "", "pproc_create_ts": "", "fd": 39, "open_flags": 4098, "res": "/dev/console", "proto": "", "sport": "", "dport": "", "sip": "", "dip": "", "rcv_r_bytes": 0, "rcv_r_ops": 0, "snd_w_bytes": 133, "snd_w_ops": 1, "cont_id": "dd629a3b1e89", "cont_name": "incomplete", "cont_image_id": "incomplete", "cont_image": "incomplete/incomplete", "cont_type": "CT_DOCKER", "cont_privileged": false}'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 944, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "./exporter.py", line 220, in <module>
    exporter.run()
  File "/usr/local/exporter/executor.py", line 44, in run
    self.func(*self.params)
  File "./exporter.py", line 94, in run
    export_to_syslogger(args, logger)
  File "./exporter.py", line 110, in export_to_syslogger
    formatter.applyFuncJson(lambda sf: rsyslog(logger, sf, args.syslogexpint), fields)
  File "/usr/local/lib/python3.6/site-packages/sysflow-0.1-py3.6.egg/sysflow/formatter.py", line 172, in applyFuncJson
    func(json.dumps(record))
  File "./exporter.py", line 110, in <lambda>
    formatter.applyFuncJson(lambda sf: rsyslog(logger, sf, args.syslogexpint), fields)
  File "./exporter.py", line 72, in rsyslog
    logger.info(msg)

Message: '{"flow_type": "FF", "op_flags": "O  W    C  ", "ret_code": "", "ts": "02/05/2020T21:48:36.505842", "ts_uts": 1580939316505842351, "end_ts": "02/05/2020T21:48:36.505912", "end_ts_uts": 1580939316505911652, "proc_pid": 1, "proc_tid": 1, "proc_uid": 0, "proc_user": "root", "proc_gid": 0, "proc_group": "root", "proc_exe": "/usr/local/sysflow/bin/sysporter", "proc_args": "-G 60 -w /mnt/data/ -e ubuntu3 -f container.name!=sf-collector and container.name!=sf-exporter", "proc_tty": false, "proc_create_ts": 1580857027654511431, "pproc_pid": "", "pproc_gid": "", "pproc_uid": "", "pproc_group": "", "pproc_tty": "", "pproc_user": "", "pproc_exe": "", "pproc_args": "", "pproc_create_ts": "", "fd": 39, "open_flags": 4098, "res": "/dev/console", "proto": "", "sport": "", "dport": "", "sip": "", "dip": "", "rcv_r_bytes": 0, "rcv_r_ops": 0, "snd_w_bytes": 133, "snd_w_ops": 1, "cont_id": "dd629a3b1e89", "cont_name": "incomplete", "cont_image_id": "incomplete", "cont_image": "incomplete/incomplete", "cont_type": "CT_DOCKER", "cont_privileged": false}'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 944, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "./exporter.py", line 220, in <module>
    exporter.run()
  File "/usr/local/exporter/executor.py", line 44, in run
    self.func(*self.params)
  File "./exporter.py", line 94, in run
    export_to_syslogger(args, logger)
  File "./exporter.py", line 110, in export_to_syslogger
    formatter.applyFuncJson(lambda sf: rsyslog(logger, sf, args.syslogexpint), fields)
  File "/usr/local/lib/python3.6/site-packages/sysflow-0.1-py3.6.egg/sysflow/formatter.py", line 172, in applyFuncJson
    func(json.dumps(record))
  File "./exporter.py", line 110, in <lambda>
    formatter.applyFuncJson(lambda sf: rsyslog(logger, sf, args.syslogexpint), fields)
  File "./exporter.py", line 72, in rsyslog
    logger.info(msg)
Message: '{"flow_type": "FF", "op_flags": "O  W    C  ", "ret_code": "", "ts": "02/05/2020T21:48:36.505842", "ts_uts": 1580939316505842351, "end_ts": "02/05/2020T21:48:36.505912", "end_ts_uts": 1580939316505911652, "proc_pid": 1, "proc_tid": 1, "proc_uid": 0, "proc_user": "root", "proc_gid": 0, "proc_group": "root", "proc_exe": "/usr/local/sysflow/bin/sysporter", "proc_args": "-G 60 -w /mnt/data/ -e ubuntu3 -f container.name!=sf-collector and container.name!=sf-exporter", "proc_tty": false, "proc_create_ts": 1580857027654511431, "pproc_pid": "", "pproc_gid": "", "pproc_uid": "", "pproc_group": "", "pproc_tty": "", "pproc_user": "", "pproc_exe": "", "pproc_args": "", "pproc_create_ts": "", "fd": 39, "open_flags": 4098, "res": "/dev/console", "proto": "", "sport": "", "dport": "", "sip": "", "dip": "", "rcv_r_bytes": 0, "rcv_r_ops": 0, "snd_w_bytes": 133, "snd_w_ops": 1, "cont_id": "dd629a3b1e89", "cont_name": "incomplete", "cont_image_id": "incomplete", "cont_image": "incomplete/incomplete", "cont_type": "CT_DOCKER", "cont_privileged": false}'

**To reproduce**
1. push the logs to rsyslog for several hours.

**Environment (please complete the following information):**
 OS: Ubuntu 18.04.3 LTS
Kernel: Linux 5.3.0-26-generic
Architecture: x86-64
SysFlow version: sf-collector:edge
Container runtime: Docker

**Comment by mutazalsallal** [comment]
I ran the exporter as following:

> docker run -d --name sf-exporter -v /mnt/data:/mnt/data -e EXPORT_TYPE=syslog -e SYSLOG_HOST=192.168.0.45 -e SYSLOG_PORT=514 -e SYSLOG_PROTOCOL=TCP -e NODE_IP=${HOSTNAME} -e INTERVAL=0.1 sysflowtelemetry/sf-exporter

**Comment by mutazalsallal** [comment]
I think its because the interval is too low, but that should not be an issue, I used syslog-ng to send syslog at rate 1000 events per second and it was fine
