### ISSUE TITLE
exporter Error while decompressing data: incomplete or truncated stream

### ISSUE THREAD

**Issue by mutazalsallal** [sysflow-telemetry/sf-docs#40]
**Indicate project**
sf-exporter:latest

**Describe the bug**
my machine suddenly turned off, when logged in again, I found the sf-exporter container with the following error, I can't reproduce it, I think its fine as my machine power turned off, this is the stack trace just in case:

my assumption is that as my machine suddenly turned off, the collector maybe at that time was writing out some data to a file, then my machine turned off, so the written file is not complete, I think we should handle this exception and try to read the next record or the next file.

> 2020-04-17 12:29:58,665 [INFO]  Read configuration from 'stdin'; logging to 'stdout'
2020-04-17 12:29:58,665 [INFO]  Running monitor task with host: localhost:9000, bucket: sf-monitoring, scaninterval: 10.0s
2020-04-17 12:33:17,934 [ERROR] Error while executing exporter
Traceback (most recent call last):
  File "./exporter.py", line 218, in <module>
    exporter.run()
  File "/usr/local/exporter/executor.py", line 44, in run
    self.func(*self.params)
  File "./exporter.py", line 93, in run
    export_to_syslogger(args, logger)
  File "./exporter.py", line 109, in export_to_syslogger
    formatter.applyFuncJson(lambda sf: rsyslog(logger, sf, args.syslogexpint), fields)
  File "/usr/local/lib/python3.6/site-packages/sysflow-0.1-py3.6.egg/sysflow/formatter.py", line 174, in applyFuncJson
    for r in self.sfqlint.filter(self.reader, expr, self.defs):
  File "/usr/local/lib/python3.6/site-packages/sysflow-0.1-py3.6.egg/sysflow/reader.py", line 165, in __next__
    sf = super().next()
  File "/usr/local/lib/python3.6/site-packages/sysflow-0.1-py3.6.egg/sysflow/reader.py", line 69, in next
    return next(self.reader)
  File "/usr/local/lib/python3.6/site-packages/avro_python3-1.9.1-py3.6.egg/avro/datafile.py", line 522, in __next__
    self._read_block_header()
  File "/usr/local/lib/python3.6/site-packages/avro_python3-1.9.1-py3.6.egg/avro/datafile.py", line 489, in _read_block_header
    uncompressed = zlib.decompress(data, -15)
zlib.error: Error -5 while decompressing data: incomplete or truncated stream

**Environment (please complete the following information):**
- OS: Ubuntu 18.04.3 LTS
- Kernel: Linux 5.3.0-26-generic
- Architecture: x86-64
- SysFlow version: sf-exporter:latest
 - Container runtime: docker
 - Command line: docker run -d --name sf-exporter -v /mnt/data:/mnt/data -e EXPORT_TYPE=syslog -e SYSLOG_HOST=192.168.0.45 -e SYSLOG_PORT=514 -e SYSLOG_PROTOCOL=TCP -e NODE_IP=${HOSTNAME} -e INTERVAL=10 sysflowtelemetry/sf-exporter

**Comment by araujof** [comment]
The syslog feature of the exporter is being deprecated in favor of the more robust processor rsyslog export.
